<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >



    <!-- Camera properties -->
    <xacro:property name="hfov" value="1.089" /> 
    <xacro:property name="cam_width" value="640" /> 
    <xacro:property name="cam_height" value="480" /> 
    <xacro:property name="near" value="0.05" />
    <xacro:property name="far" value="8.0" />
    <xacro:property name="camera_height_dif" value="0.5" />
    <xacro:property name="camera_size_x" value="0.03" />
    <xacro:property name="camera_size_y" value="0.1" />
    <xacro:property name="camera_size_z" value="0.1" />
    

    <joint name="camera_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="camera_link"/>
        <origin xyz="${base_length/2 + camera_size_x/2 } 0 ${base_height - camera_height_dif}" rpy="0 0 0"/>
    </joint>
    

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_size_x} ${camera_size_y} ${camera_size_z}"/>
            </geometry>
            <material name="red"/>
        </visual>
    </link>

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}"/>
    </joint>

    <link name="camera_link_optical"></link>
    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>
        <sensor name="camera" type="camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>${hfov}</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>${cam_width}</width>
                    <height>${cam_height}</height>
                </image>
                <clip>
                    <near>${near}</near>
                    <far>${far}</far>
                </clip>
            </camera>
            <!-- <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link_optical</frame_name>
            </plugin> -->
            <plugin name="gazebo_ros_camera" filename="libgazebo_ros_camera.so">
                <robotNamespace>/</robotNamespace>
                <cameraName>camera</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>camera_link_optical</frameName>
            </plugin>
        </sensor>
    </gazebo>

</robot>