###############################################################################
# This is default configuration.

version: 0.9

######################################################
## driving strategy - run_neural.py

# max vel
max_vel: 100
# steering angle value for sharp turn
sharp_turn_min: 0.25
# when sharp turn, apply brake for this sec.
brake_apply_sec: 1.7
# brake value
brake_val: 1
# throttle at non sharp turn
throttle_default: 0.3
# throttle at sharp turn
throttle_sharp_turn: 0.3
# velocity threshold for not moving
velocity_0: 30
# scale factors
scale_factor_throttle: 0.3
scale_factor_steering: 0.3
