controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rear_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    steering_position_controller:
      type: position_controllers/JointGroupPositionController

rear_velocity_controller:
  ros__parameters:
    joints:
      - rear_left_wheel_joint
      - rear_right_wheel_joint
      - front_left_wheel_joint
      - front_right_wheel_joint
    pid: { p: 100.0, i: 0.01, d: 10.0 }
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

steering_position_controller:
  ros__parameters:
    joints:
      - front_left_steering_joint
      - front_right_steering_joint
    pid: { p: 100.0, i: 0.01, d: 10.0 }
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
