controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    bicycle_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['rear_left_wheel_joint']
    right_wheel_names: ['rear_right_wheel_joint']
    wheel_separation: 0.0.80
    wheel_radius: 0.1397

    use_stamped_vel: false

    # open_loop: false    
bicycle_steering_controller:
  ros__parameters:
    # rear_wheel_name: "rear_right_wheel_joint"
    # rear_wheel_name: "rear_left_wheel_joint"
    front_steer_name: "front_right_wheel_joint"
    front_steer_name: "front_left_wheel_joint"
    base_frame_id: base_link

    publish_rate: 50.0
    # # rear_wheels: ['rear_right_wheel_joint', 'rear_left_wheel_joint']
    # left_wheel_names: ["rear_left_wheel_joint", "front_left_wheel_joint"]
    # right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]
    wheel_separation_h: 0.80
    wheel_separation: 0.80
    wheel_radius: 0.1397
    enable_odom_tf: true
    open_loop: true
    use_stamped_vel: false
    pose_covariance_diagonal:
      [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal:
      [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]



# joint_broad:
#   ros__parameters: