controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    # use_sim_time: true

    joint_state_b:
      type: joint_state_broadcaster/JointStateBroadcaster

    bicycle_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    position_controller:
      type: position_controllers/JointGroupPositionController

bicycle_steering_controller:
  ros__parameters:
    rear_wheel_name: "rear_right_wheel_joint"
    rear_wheel_name: "rear_left_wheel_joint"
    front_steer_name: "front_right_steering_joint"
    front_steer_name: "front_left_steering_joint"
    base_frame_id: base_link

    publish_rate: 50.0
    wheel_separation_h: 0.80
    wheel_separation: 0.80
    wheel_radius: 0.1397
    enable_odom_tf: true
    open_loop: true
    use_stamped_vel: false
    pose_covariance_diagonal:
      [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal:
      [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

# velocity_controller:
#   ros__parameters:
#     joints:
#       - virtual_rear_wheel_joint
# position_controller:
#   ros__parameters:
#     joints:
#       - virtual_front_wheel_joint