<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="materials.xacro"/>


    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_mass" value="8.0" /> <!-- arbitrary value for base mass -->
    <xacro:property name="base_width" value="0.94" />
    <xacro:property name="base_length" value="1.3" />
    <xacro:property name="base_height" value="0.83" />
    <xacro:property name="wheelbase" value="0.8" />
    <xacro:property name="wheel_mass" value="0.34055" /> <!-- arbitrary value for wheel mass -->
    <xacro:property name="wheel_len" value="0.125" />
    <xacro:property name="wheel_radius" value="0.1397" />
    <!-- <xacro:property name="wheeltrack" value="" -->

    <!-- Base Link -->
    <link name="base_link" />

    <!-- Chassis -->

    <link name="chassis_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${base_mass}"/>
            <inertia
                ixx="0.000270" ixy="0.0" ixz="0.0"
                iyy="0.000270" iyz="0.0"
                izz="0.000426"/>
        </inertial>
    </link>
    <gazebo reference="chassis_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="0 0 ${base_height/2 + wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.2"/>
    </joint>


    <!-- rear wheels -->

    <!-- virtual rear wheel -->

    <!-- <link name="virtual_rear_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <geometry>
                <cylinder length="0.01" radius="${wheel_radius}"/>
            </geometry>
            <material name="invisible"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <geometry>
                <cylinder length="0.01" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <mass value="${wheel_mass}"/>
            <inertia
                ixx="0.000270" ixy="0.0" ixz="0.0"
                iyy="0.000270" iyz="0.0"
                izz="0.000426"/>
        </inertial>
    </link>
    <gazebo reference="virtual_rear_wheel">
        <material>Gazebo/GreyTransparent</material>
    </gazebo> -->

    <!-- <joint name="virtual_rear_wheel_joint" type="continuous">
        <parent link="chassis_link"/>
        <child link="virtual_rear_wheel"/>
        <origin xyz="-${wheelbase/2} 0 -${base_height/2}" rpy="0 0 ${PI/2}"/>
        <axis xyz="1 0 0"/>
        <limit effort="100.0" velocity="100.0"/>
        <dynamics damping="0.2"/>
    </joint> -->

    <!-- rear right wheel -->

    <link name="rear_right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <geometry>
                <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <geometry>
                <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <mass value="${wheel_mass}"/>
            <inertia
                ixx="0.000270" ixy="0.0" ixz="0.0"
                iyy="0.000270" iyz="0.0"
                izz="0.000426"/>
        </inertial>
    </link>
    <gazebo reference="rear_right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="chassis_link"/>
        <child link="rear_right_wheel"/>
        <origin xyz="-${wheelbase/2} ${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
        <axis xyz="1 0 0"/>
        <limit effort="100.0" velocity="100.0"/>
        <dynamics damping="0.2"/>
        <!-- <mimic joint="virtual_rear_wheel_joint" multiplier="1.0" offset="0.0"/> -->
    </joint>

    <!-- rear left wheel -->
    <link name="rear_left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <geometry>
                <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <geometry>
                <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <mass value="${wheel_mass}"/>
            <inertia
            ixx="0.000270" ixy="0.0" ixz="0.0"
            iyy="0.000270" iyz="0.0"
            izz="0.000426"/>
        </inertial>
    </link>
    <gazebo reference="rear_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="chassis_link" />
        <child link="rear_left_wheel" />
        <origin xyz="-${wheelbase/2} -${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
        <axis xyz="1 0 0"/>
        <limit effort="100.0" velocity="100.0"/>
        <dynamics damping="0.2"/>
        <!-- <mimic joint="virtual_rear_wheel_joint" multiplier="1.0" offset="0.0"/> -->
    </joint>

    <!-- front wheels -->

    <!-- virtual front wheel -->

    <!-- <link name="virtual_front_wheel">
        <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
            <cylinder length="0.01" radius="${wheel_radius}"/>
        </geometry>
        <material name="invisible"/>
        </visual>
        <collision>
                <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
                <geometry>
                    <cylinder length="0.01" radius="${wheel_radius}"/>
                </geometry>
        </collision>
        <inertial>
                <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
                <mass value="${wheel_mass}"/>
                <inertia
                    ixx="0.000270" ixy="0.0" ixz="0.0"
                    iyy="0.000270" iyz="0.0"
                    izz="0.000426"/>
        </inertial>
    </link>
    <gazebo reference="virtual_front_wheel">
        <material>Gazebo/GreyTransparent</material>
    </gazebo> -->

    <!-- <joint name="virtual_front_wheel_joint" type="revolute">
        <parent link="chassis_link"/>
        <child link="virtual_front_wheel"/>
        <origin xyz="${wheelbase/2} 0 -${base_height/2}" rpy="0 0 ${PI/2}"/>
        <axis xyz="0 0 1"/>
        <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0"/>
        <dynamics damping="0.2"/>
    </joint> -->

    <!-- front right wheel -->


    <link name="front_right_wheel">   
        <visual>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <geometry>
                <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <geometry>
                <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <mass value="${wheel_mass}"/>
            <inertia
                ixx="0.000270" ixy="0.0" ixz="0.0"
                iyy="0.000270" iyz="0.0"
                izz="0.000426"/>
        </inertial>
    </link>
    <gazebo reference="front_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="front_right_steering_joint" type="revolute">
        <parent link="chassis_link" />
        <child link="front_right_wheel" />
        <origin xyz="${wheelbase/2} ${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
        <axis xyz="1 0 1"/>
        <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0"/>
        <dynamics damping="0.2"/>
        <!-- <mimic joint="virtual_front_wheel_joint" multiplier="1.0" offset="0.0"/> -->
    </joint>

    <!-- <joint name="front_right_wheel_joint" type="continuous">
        <parent link="chassis_link" />
        <child link="front_right_wheel" />
        <origin xyz="${wheelbase/2} ${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
        <axis xyz="1 0 0"/>
        <limit effort="100.0" velocity="0.0"/>
        <dynamics damping="0.2"/>
    </joint> -->

    <!-- front right steering -->
    

    <!-- front left steering -->


    <link name="front_left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <geometry>
                <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <geometry>
                <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
            <mass value="${wheel_mass}"/>
            <inertia
                ixx="0.000270" ixy="0.0" ixz="0.0"
                iyy="0.000270" iyz="0.0"
                izz="0.000426"/>
        </inertial>

    </link>
    <gazebo reference="front_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    
    <joint name="front_left_steering_joint" type="revolute">
        <parent link="chassis_link" />
        <child link="front_left_wheel" />
        <origin xyz="${wheelbase/2} -${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
        <axis xyz="0 0 1"/>
        <limit lower="-0.4" upper="0.4" effort="100.0" velocity="0.0"/>
        <dynamics damping="0.2"/>
    </joint>

  



</robot>