# ... below the joy parameters

teleop_node:
  ros__parameters:
    axis_linear: # Left thumb stick vertical
      x: 3
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular: # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0

    require_enable_button: true
    enable_button: 5 # Left shoulder button
    enable_turbo_button: 6 # Right shoulder button
