<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="materials.xacro"/>


    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_mass" value="8.0" /> <!-- arbitrary value for base mass -->
    <xacro:property name="base_width" value="0.94" />
    <xacro:property name="base_length" value="1.3" />
    <xacro:property name="base_height" value="0.83" />
    <xacro:property name="wheelbase" value="0.8" />
    <xacro:property name="wheel_mass" value="0.34055" /> <!-- arbitrary value for wheel mass -->
    <xacro:property name="wheel_len" value="0.125" />
    <xacro:property name="wheel_radius" value="0.1397" />
    <xacro:property name="length" value="1.3" />
    <xacro:property name="width" value="0.94" />
    <xacro:property name="thickness" value="0.086" /> <!-- Link 2 -->
    <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->
    <xacro:property name="steer_offset" value="0.02" /> <!-- Link 1 -->
    <xacro:property name="steer_radius" value="0.05" /> <!-- Link 1 -->
    <xacro:property name="steer_thickness" value="0.02" /> <!-- Link 1 -->
    <xacro:property name="steer_effort"   value="10.0"/>
    <xacro:property name="steer_velocity" value="5.0"/>
    <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>
    <!-- <xacro:property name="wheeltrack" value="" -->

    <!-- Base Link -->
    <link name="base_link" />

    <!-- Chassis -->

    <link name="chassis_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${base_mass}"/>
            <inertia
                ixx="0.000270" ixy="0.0" ixz="0.0"
                iyy="0.000270" iyz="0.0"
                izz="0.000426"/>
        </inertial>
    </link>
    <gazebo reference="chassis_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="0 0 ${base_height/2 + wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.2"/>
    </joint>




    <!-- Steer Front     -->

    <link name="front_steer_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${steer_thickness}" radius="${steer_radius}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${steer_thickness}" radius="${steer_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia
                ixx="0.000270" ixy="0.0" ixz="0.0"
                iyy="0.000270" iyz="0.0"
                izz="0.000426"/>
        </inertial>

    </link>
    <gazebo reference="front_steer_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <joint name="front_steer_joint" type="revolute">
        <parent link="chassis_link" />
        <child link="front_steer_link" />
        <origin xyz="${length/2.5} ${width/30} ${base_height/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="${steer_effort}" lower="${-45.0 * deg_to_rad}" upper="${45.0 * deg_to_rad}" velocity="${steer_velocity}"/>
        
    </joint>






    <!-- rear     -->
    <link name="rear_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_len*7.2}" radius="${wheel_radius/4}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_len*7.2}" radius="${wheel_radius/4}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia
            ixx="0.000270" ixy="0.0" ixz="0.0"
            iyy="0.000270" iyz="0.0"
            izz="0.000426"/>
        </inertial>
    </link>
    <gazebo reference="rear_wheel_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="rear_wheel_joint" type="continuous">
        <parent link="chassis_link" />
        <child link="rear_wheel_link"/>
        <origin xyz="${-length/2+axel_offset} 0 ${-base_height/2}" rpy="${-90 * deg_to_rad} 0 0"/>
        <axis xyz="0 0 1"/>
        
    </joint>



    <!-- Wheels     -->

    
    <link name="front_right_steer_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${steer_radius}" length="${steer_thickness}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${steer_radius}" length="${steer_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia
                ixx="0.000270" ixy="0.0" ixz="0.0"
                iyy="0.000270" iyz="0.0"
                izz="0.000426"/>
        </inertial>
        
    </link>
    <gazebo reference="front_right_steer_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <joint name="front_right_steer_joint" type="revolute">
        <parent link="chassis_link" />
        <child link="front_right_steer_link" />
        <origin xyz="${length/2-axel_offset} ${width/2+axel_offset} ${-(base_height/2-wheel_radius+steer_offset)}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="${steer_effort}" lower="${-45.0* deg_to_rad}" upper="${45.0 * deg_to_rad}" velocity="${steer_velocity}"/>
        <!-- <mimic joint="front_steer_joint" multiplier="1.0" offset="0.0"/> -->
    </joint>


    <link name="front_left_steer_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${steer_radius}" length="${steer_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${steer_radius}" length="${steer_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia
                ixx="0.000270" ixy="0.0" ixz="0.0"
                iyy="0.000270" iyz="0.0"
                izz="0.000426"/>
        </inertial>

    </link>
    <gazebo reference="front_left_steer_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <joint name="front_left_steer_joint" type="revolute">
        <parent link="chassis_link" />
        <child link="front_left_steer_link" />
        <origin xyz="${length/2-axel_offset} ${-width/2-axel_offset} ${-(base_height/2-wheel_radius-steer_offset)}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="${steer_effort}" lower="${-45.0 * deg_to_rad}" upper="${45.0 * deg_to_rad}" velocity="${steer_velocity}"/>
        <!-- <mimic joint="front_steer_joint" multiplier="1.0" offset="0.0"/> -->

    </joint>

    <link name="front_right_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_len}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_len}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia
                ixx="0.000270" ixy="0.0" ixz="0.0"
                iyy="0.000270" iyz="0.0"
                izz="0.000426"/>
        </inertial>

    </link>
    <gazebo reference="front_right_wheel_link">
        <material>Gazebo/Blue</material>
    </gazebo>
    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="front_right_steer_link"/>
        <child link="front_right_wheel_link"/>
        <origin xyz="0 0 ${-(wheel_radius+steer_offset)}" rpy="${-90 * deg_to_rad} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="front_left_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_len}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_len}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia
                ixx="0.000270" ixy="0.0" ixz="0.0"
                iyy="0.000270" iyz="0.0"
                izz="0.000426"/>
        </inertial>

    </link>
    <gazebo reference="front_left_wheel_link">
        <material>Gazebo/Blue</material>
    </gazebo>
    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="front_left_steer_link"/>
        <child link="front_left_wheel_link"/>
        <origin xyz="0 0 ${-(wheel_radius+steer_offset)}" rpy="${-90 * deg_to_rad} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>



    <link name="rear_right_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia
            ixx="0.000270" ixy="0.0" ixz="0.0"
            iyy="0.000270" iyz="0.0"
            izz="0.000426"/>
        </inertial>
    </link>
    <gazebo reference="rear_right_wheel_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="chassis_link" />
        <child link="rear_right_wheel_link" />
        <origin xyz="${-length/2+axel_offset} ${width/2+axel_offset} ${-base_height/2}" rpy="${-90 * deg_to_rad} 0 0"/>
        <axis xyz="0 0 1"/>  
        <!-- <mimic joint="rear_wheel_joint" multiplier="1.0" offset="0.0"/> -->
 
    </joint>



    <link name="rear_left_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia
            ixx="0.000270" ixy="0.0" ixz="0.0"
            iyy="0.000270" iyz="0.0"
            izz="0.000426"/>
        </inertial>
    </link>
    <gazebo reference="rear_left_wheel_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="chassis_link" />
        <child link="rear_left_wheel_link" />
        <origin xyz="${-length/2+axel_offset} ${-width/2-axel_offset} ${-base_height/2}" rpy="${-90 * deg_to_rad} 0 0"/>
        <axis xyz="0 0 1"/>   
        <!-- <mimic joint="rear_wheel_joint" multiplier="1.0" offset="0.0"/> -->

    </joint>

</robot>