# commandTopic: cmd_vel
# odometryTopic: odom
# odometryFrame: odom
# robotBaseFrame: base_footprint
# publishWheelTF: false
# publishOdomTF: true
# publishWheelJointState: false
# wheelseparation: 0.80
# wheelDiameter: .0.2794
# wheelAcceleration: 0.0
# WheelTorque: 5.0
# updateRate: 100.0
# odometrySource: world

steer_bot_hardware_gazebo:
    rear_wheel  : 'virtual_rear_wheel_joint'
    front_steer : 'virtual_front_steer_joint'
    virtual_rear_wheels  : ['rear_right_wheel_joint', 'rear_left_wheel_joint']
    virtual_front_wheels : ['front_right_wheel_joint', 'front_left_wheel_joint']
    virtual_front_steers : ['front_right_steer_joint', 'front_left_steer_joint']

    # ackermann link mechanism
    enable_ackermann_link: true
    wheel_separation_h : 0.80