ekf_se_odom:
  frequency: 30
  sensor_timeout: 0.1
  two_d_mode: true
  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  odom0: /odom
  odom0_config:
    [
      false,
      false,
      false,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
      true,
      true,
    ]

  imu0: /mavros/imu/data
  imu0_config:
    [
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
      true,
      true,
      true,
      true,
      false,
      false,
      false,
    ]

  imu0_differential: false
  imu0_remove_gravitational_acceleration: true

  publish_tf: true
  publish_acceleration: false
  use_control: false
