# =======
# joy_dev: "/dev/input/js0"
deadzone: 0.05

axis_linear: 3 # Left thumb stick vertical
scale_linear: 0.2
scale_linear_turbo: 0.5

axis_angular: 0 # Left thumb stick horizontal
scale_angular: 0.4

require_enable_button: false
enable_button: 0 # Left trigger button
enable_turbo_button: 1 # Right trigger button
